name: echo something

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Hello, world!
