name: fetch stations
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:  # allows running manually from the Actions tab
jobs:
  fetch-stations:
    runs-on: ubuntu-latest
    steps:
      - env:
          STYRSTALL_API_KEY: ${{ secrets.STYRSTALL_API_KEY }}
        run: |
          curl --max-time 60 \
          https://data.goteborg.se/SelfServiceBicycleService/v2.0/Stations/$STYRSTALL_API_KEY?format=json \
          > stations.json
      - uses: actions/upload-artifact@v4
        with:
          path: stations.json
          retention-days: ${{ env.RETENTION_DAYS }}
